Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "config-update.sh"
  config.vm.define "nodo1" do |nodo1|
    nodo1.vm.box = "bento/ubuntu-16.04"
    nodo1.vm.network "private_network", ip:"192.168.33.11"
    nodo1.vm.network "forwarded_port", guest: 80, host: 8080
    nodo1.vm.hostname = "loadbalancer"
    nodo1.vm.provider "virtualbox" do |vm|
      vm.name = "loadbalancer"
      vm.memory = "512"
      vm.gui = true
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo2" do |nodo2|
    nodo2.vm.box = "bento/ubuntu-16.04"
    nodo2.vm.network "private_network", ip:"192.168.33.12"
    nodo2.vm.network "forwarded_port", guest: 80, host: 8081
    nodo2.vm.hostname = "web1"
    nodo2.vm.provider "virtualbox" do |vm|
      vm.name = "web1"
      vm.memory = "1024"
      vm.gui = true
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo3" do |nodo3|
    nodo3.vm.box = "bento/ubuntu-16.04"
    nodo3.vm.network "private_network", ip:"192.168.33.13"
    nodo3.vm.network "forwarded_port", guest: 80, host: 8082
    nodo3.vm.hostname = "web2"
    nodo3.vm.provider "virtualbox" do |vm|
      vm.name = "web2"
      vm.memory = "512"
      vm.gui = true
      vm.cpus = "1"
    end
  end
  config.vm.define "nodo4" do |nodo4|
    nodo4.vm.box = "bento/ubuntu-16.04"
    nodo4.vm.network "private_network", ip:"192.168.33.14"
    nodo4.vm.network "forwarded_port", guest: 3306, host: 33006
    nodo4.vm.hostname = "basededatos"
    nodo4.vm.provider "virtualbox" do |vm|
      vm.name = "basededatos"
      vm.memory = "768"
      vm.gui = false
      vm.cpus = "1"
    end
  end
end
