Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip:"192.168.33.10"
  config.vm.hostname = "master"
  #Debe existir una carpeta shared en la carpeta del proyecto, del vagrantfile
  config.vm.synced_folder "shared", "/home/vagrant/projects"
  config.vm.provision "shell", path: "config-ansible.sh"
  config.vm.provider "virtualbox" do |vm|
  	vm.name = "master"
  	vm.memory = "256"
  	vm.cpus = "1"
	end
end
